repos:
  - repo: https://github.com/aio-libs/sort-all
    rev: v1.3.0
    hooks:
      - id: sort-all
  - repo: https://github.com/bwhmather/ssort
    rev: 0.14.0
    hooks:
      - id: ssort
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.6
    hooks:
      - id: docformatter
        args: [--in-place, --close-quotes-on-newline, --wrap-summaries=72]
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        files: ^src/
        types: [python]
