name: bump

on:
  push:
    branches:
      - main
    paths:
      - 'ignition-project/**'
      - 'jython-package/**'
      - 'python2-package/**'
      - 'python3-stubs/**'
      - 'copier.yml'

jobs:
  bump:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.COATL_BOT_GH_TOKEN }}

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.13'

      - name: Checkout requirements repo
        uses: actions/checkout@v4
        with:
          repository: coatl-dev/workflow-requirements
          path: deps

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ steps.setup-python.outputs.python-version }}-${{ runner.os }}-${{ hashFiles('deps/requirements/commitizen.txt') }}

      - name: Install requirements
        run: |
          python -m pip install --requirement deps/requirements/commitizen.txt

      - uses: coatl-dev/actions/gpg-import@v3
        id: gpg-import
        with:
          passphrase: ${{ secrets.COATL_BOT_GPG_PASSPHRASE }}
          private-key: ${{ secrets.COATL_BOT_GPG_PRIVATE_KEY }}

      - run: |
          cz bump

      - run: |
          git push origin HEAD --tags
