name: bump

on:
  push:
    branches:
      - main

jobs:
  bump:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.COATL_BOT_GH_TOKEN }}

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.x'

      - run: |
          python -m pip install commitizen

      - uses: coatl-dev/actions/gpg-import@v3
        id: gpg-import
        with:
          passphrase: ${{ secrets.COATL_BOT_GPG_PASSPHRASE }}
          private-key: ${{ secrets.COATL_BOT_GPG_PRIVATE_KEY }}

      - run: |
          cz bump

      - uses: coatl-dev/actions/simple-git-diff@v3
        id: git-diff

      - if: ${{ steps.git-diff.outputs.diff == 'true' }}
        run: |
          git push origin HEAD --tags
