on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: coatl-dev/actions/gpg-import@v3
        id: gpg-import
        with:
          passphrase: ${{ secrets.COATL_BOT_GPG_PASSPHRASE }}
          private-key: ${{ secrets.COATL_BOT_GPG_PRIVATE_KEY }}

      - uses: commitizen-tools/commitizen-action@0.21.0
        with:
          github_token: ${{ secrets.COATL_BOT_GH_TOKEN }}
