name: bump

on:
  push:
    branches:
      - main

jobs:
  bump:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.COATL_BOT_GH_TOKEN }}

      - uses: coatl-dev/actions/gpg-import@v3
        id: gpg-import
        with:
          passphrase: ${{ secrets.COATL_BOT_GPG_PASSPHRASE }}
          private-key: ${{ secrets.COATL_BOT_GPG_PRIVATE_KEY }}

      - uses: commitizen-tools/commitizen-action@0.21.0
        with:
          push: false
          git_email: ${{ steps.gpg-import.outputs.git-user-email }}
          git_name: ${{ steps.gpg-import.outputs.git-user-name }}
          gpg_sign: true
        env:
          PIP_NO_CACHE_DIR: 1
          PIP_ROOT_USER_ACTION: ignore

      - run: |
          git push origin HEAD --tags
