name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: ${{ startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.COATL_BOT_GH_TOKEN }}

      - id: tag
        run: |
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - run: |
          gh release create "$TAG" \
            --generate-notes
        env:
          TAG: ${{ steps.tag.outputs.tag }}
          GITHUB_TOKEN: ${{ secrets.COATL_BOT_GH_TOKEN }}
