name: release

on:
  push:
    branches:
      - main
    tags:
      - '**'

jobs:

  release:
    if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          gh release create "$TAG" \
            --title "$TAG" \
            --generate-notes
        env:
          TAG: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.COATL_BOT_GH_TOKEN }}
