name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: ${{ startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.COATL_BOT_GH_TOKEN }}

      - run: |
          TAG=$(git describe --tags --abbrev=0)
          gh release create "$TAG" \
            --title "$TAG" \
            --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.COATL_BOT_GH_TOKEN }}
